<nav class="navbar">
  <a href="/">Home</a>
  <a href="/acts">Acts</a>
  <a href="/accommodation">Accommodation</a>
</nav>

<style>
  nav {
    background-color: #3c1c00;
    padding: 30px;
  }

  nav a {
    color: #ede6c6;
    background-color: #a34f04;
    padding: 12px;
    margin-right: 5%;
    font-family: "Belanosima", sans-serif;
    font-size: 150%;
  }

  @media (max-width: 550px) {
    nav a {
      padding: 7px;
      margin-right: 3%;
      font-size: 110%;
    }
  }
</style>
