<nav>
  <a href="/">Home</a>
  <a href="/acts">Acts</a>
  <a href="/accommodation">Accommodation</a>
</nav>

<style>
  nav {
    background-color: #3c1c00;
    padding: 30px;
  }

  nav a {
    color: #ede6c6;
    background-color: #a34f04;
    padding: 12px;
    margin: 20px;
    font-family: "Belanosima", sans-serif;
    font-size: 150%;
  }

  @media (max-width: 550px) {
    a {
      margin-top: 50px;
    }
  }
</style>
